-- MySQL Script generated by MySQL Workbench
-- Thu Mar 31 15:24:27 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema groot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NULL DEFAULT NULL,
  `role_input_date` TIMESTAMP NULL DEFAULT NULL,
  `role_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NULL DEFAULT NULL,
  `user_full_name` VARCHAR(255) NULL DEFAULT NULL,
  `user_password` VARCHAR(45) NULL DEFAULT NULL,
  `user_email` VARCHAR(45) NULL DEFAULT NULL,
  `user_description` TEXT NULL DEFAULT NULL,
  `user_image` VARCHAR(255) NULL DEFAULT NULL,
  `user_deleted` TINYINT(1) NULL DEFAULT '0',
  `user_role_id` INT(11) NULL DEFAULT NULL,
  `user_input_date` TIMESTAMP NULL DEFAULT NULL,
  `user_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_user_role1_idx` (`user_role_id` ASC),
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `user_role` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `activity_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `activity_log` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT,
  `log_date` TIMESTAMP NULL DEFAULT NULL,
  `log_action` VARCHAR(45) NULL DEFAULT NULL,
  `log_module` VARCHAR(45) NULL DEFAULT NULL,
  `log_info` TEXT NULL DEFAULT NULL,
  `log_user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_g_activity_log_g_user1_idx` (`log_user_id` ASC),
  CONSTRAINT `fk_g_activity_log_g_user1`
    FOREIGN KEY (`log_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` VARCHAR(40) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ci_sessions_timestamp` (`timestamp` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mediamanager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamanager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `isfile` TINYINT(1) NULL DEFAULT '0',
  `label` TEXT NULL DEFAULT NULL,
  `info` TEXT NULL DEFAULT NULL,
  `upload_at` DATETIME NULL DEFAULT NULL,
  `album_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `mediamanager_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamanager_album` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NULL DEFAULT NULL,
  `upload_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `posting_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posting_category` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NULL DEFAULT NULL,
  `category_input_date` TIMESTAMP NULL DEFAULT NULL,
  `category_last_update` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `posting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posting` (
  `posting_id` INT(11) NOT NULL AUTO_INCREMENT,
  `posting_title` VARCHAR(255) NULL DEFAULT NULL,
  `posting_description` TEXT NULL DEFAULT NULL,
  `posting_content` TEXT NULL DEFAULT NULL,
  `posting_published_date` TIMESTAMP NULL DEFAULT NULL,
  `posting_image` VARCHAR(255) NULL DEFAULT NULL,
  `posting_input_date` TIMESTAMP NULL DEFAULT NULL,
  `posting_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `posting_is_published` TINYINT(1) NULL DEFAULT '0' COMMENT '1 = published, 0 = draft',
  `posting_is_commentable` TINYINT(1) NULL DEFAULT '0' COMMENT '1 = commentable, 0 = uncommentable',
  `posting_category_id` INT(11) NULL,
  `posting_user_id` INT(11) NULL,
  PRIMARY KEY (`posting_id`),
  INDEX `fk_posting_posting_category1_idx` (`posting_category_id` ASC),
  INDEX `fk_posting_user1_idx` (`posting_user_id` ASC),
  CONSTRAINT `fk_posting_posting_category1`
    FOREIGN KEY (`posting_category_id`)
    REFERENCES `posting_category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_posting_user1`
    FOREIGN KEY (`posting_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting` (
  `setting_id` INT NOT NULL AUTO_INCREMENT,
  `setting_name` VARCHAR(255) NULL,
  `setting_value` VARCHAR(255) NULL,
  `setting_description` VARCHAR(255) NULL,
  PRIMARY KEY (`setting_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `contact_name` VARCHAR(255) NULL,
  `contact_value` TEXT(255) NULL,
  `contact_description` VARCHAR(255) NULL,
  PRIMARY KEY (`contact_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `page` (
  `page_id` INT(11) NOT NULL AUTO_INCREMENT,
  `page_name` VARCHAR(255) NULL DEFAULT NULL,
  `page_description` TEXT NULL DEFAULT NULL,
  `page_content` TEXT NULL DEFAULT NULL,
  `page_published_date` TIMESTAMP NULL DEFAULT NULL,
  `page_image` VARCHAR(255) NULL DEFAULT NULL,
  `page_input_date` TIMESTAMP NULL DEFAULT NULL,
  `page_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `page_is_published` TINYINT(1) NULL DEFAULT '0' COMMENT '1 = published, 0 = draft',
  `page_is_commentable` TINYINT(1) NULL DEFAULT '0' COMMENT '1 = commentable, 0 = uncommentable',
  `page_user_id` INT(11) NULL,
  PRIMARY KEY (`page_id`),
  INDEX `fk_posting_user1_idx` (`page_user_id` ASC),
  CONSTRAINT `fk_posting_user10`
    FOREIGN KEY (`page_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
